### ISSUE TITLE
please take note of upcoming i18next v2

### ISSUE THREAD

**Issue by jamuhl** [kvaillant/i18next.couchbase#2]
http://i18next.github.io/i18next.com/

adding your backend would be welcome if v2 compatible: http://i18next.github.io/i18next.com/docs/ecosystem/#backends

**Comment by kvaillant** [comment]
Hi,
Sorry for being late, I had much work to do :)
I upgrade my lib to have support for i18next v2.
Feel free to share it on i18next 2 website#backends

**Comment by jamuhl** [comment]
great...thanks...added http://i18next.com/docs/ecosystem/#backends
